export const cities = [
  { id: 1, name: "New York" },
  { id: 2, name: "Los Angeles" },
  { id: 3, name: "Chicago" },
  { id: 4, name: "Houston" },
  { id: 5, name: "Phoenix" },
  { id: 6, name: "Philadelphia" },
  { id: 7, name: "San Antonio" },
  { id: 8, name: "San Diego" },
  { id: 9, name: "Dallas" },
  { id: 10, name: "San Jose" },
  { id: 11, name: "Austin" },
  { id: 12, name: "Jacksonville" },
  { id: 13, name: "San Francisco" },
  { id: 14, name: "Charlotte" },
  { id: 15, name: "Indianapolis" },
  { id: 16, name: "Seattle" },
  { id: 17, name: "Denver" },
  { id: 18, name: "Washington" },
  { id: 19, name: "Boston" },
  { id: 20, name: "Detroit" },
  { id: 21, name: "Nashville" },
  { id: 22, name: "Memphis" },
  { id: 23, name: "Portland" },
  { id: 24, name: "Oklahoma City" },
  { id: 25, name: "Las Vegas" },
  { id: 26, name: "Louisville" },
  { id: 27, name: "Baltimore" },
  { id: 28, name: "Milwaukee" },
  { id: 29, name: "Albuquerque" },
  { id: 30, name: "Tucson" },
  { id: 31, name: "Fresno" },
  { id: 32, name: "Sacramento" },
  { id: 33, name: "Kansas City" },
  { id: 34, name: "Long Beach" },
  { id: 35, name: "Mesa" },
  { id: 36, name: "Atlanta" },
  { id: 37, name: "Colorado Springs" },
  { id: 38, name: "Virginia Beach" },
  { id: 39, name: "Raleigh" },
  { id: 40, name: "Omaha" },
  { id: 41, name: "Miami" },
  { id: 42, name: "Oakland" },
  { id: 43, name: "Minneapolis" },
  { id: 44, name: "Tulsa" },
  { id: 45, name: "Cleveland" },
  { id: 46, name: "Wichita" },
  { id: 47, name: "Arlington" },
  { id: 48, name: "New Orleans" },
  { id: 49, name: "Bakersfield" },
  { id: 50, name: "Tampa" },
  { id: 51, name: "Honolulu" },
  { id: 52, name: "Anaheim" },
  { id: 53, name: "Aurora" },
  { id: 54, name: "Santa Ana" },
  { id: 55, name: "St. Louis" },
  { id: 56, name: "Riverside" },
  { id: 57, name: "Corpus Christi" },
  { id: 58, name: "Lexington" },
  { id: 59, name: "Pittsburgh" },
  { id: 60, name: "Anchorage" },
  { id: 61, name: "Stockton" },
  { id: 62, name: "Cincinnati" },
  { id: 63, name: "St. Paul" },
  { id: 64, name: "Toledo" },
  { id: 65, name: "Greensboro" },
  { id: 66, name: "Newark" },
  { id: 67, name: "Plano" },
  { id: 68, name: "Henderson" },
  { id: 69, name: "Lincoln" },
  { id: 70, name: "Buffalo" },
  { id: 71, name: "Fort Wayne" },
  { id: 72, name: "Jersey City" },
  { id: 73, name: "Chula Vista" },
  { id: 74, name: "Orlando" },
  { id: 75, name: "St. Petersburg" },
  { id: 76, name: "Norfolk" },
  { id: 77, name: "Chandler" },
  { id: 78, name: "Laredo" },
  { id: 79, name: "Madison" },
  { id: 80, name: "Durham" },
  { id: 81, name: "Lubbock" },
  { id: 82, name: "Winston-Salem" },
  { id: 83, name: "Garland" },
  { id: 84, name: "Glendale" },
  { id: 85, name: "Hialeah" },
  { id: 86, name: "Reno" },
  { id: 87, name: "Baton Rouge" },
  { id: 88, name: "Irvine" },
  { id: 89, name: "Chesapeake" },
  { id: 90, name: "Irving" },
  { id: 91, name: "Scottsdale" },
  { id: 92, name: "North Las Vegas" },
  { id: 93, name: "Fremont" },
  { id: 94, name: "Gilbert" },
  { id: 95, name: "San Bernardino" },
  { id: 96, name: "Boise" },
  { id: 97, name: "Birmingham" },
  { id: 98, name: "Rochester" },
  { id: 99, name: "Spokane" },
  { id: 100, name: "Richmond" },
];
