export const cities = [
  { id: 1, name: "Abidjan" },
  { id: 2, name: "Addis Ababa" },
  { id: 3, name: "Adelaide" },
  { id: 4, name: "Amsterdam" },
  { id: 5, name: "Ankara" },
  { id: 6, name: "Athens" },
  { id: 7, name: "Atlanta" },
  { id: 8, name: "Auckland" },
  { id: 9, name: "Austin" },
  { id: 10, name: "Baltimore" },
  { id: 11, name: "Bangkok" },
  { id: 12, name: "Barcelona" },
  { id: 13, name: "Beijing" },
  { id: 14, name: "Berlin" },
  { id: 15, name: "Belo Horizonte" },
  { id: 16, name: "Bengaluru" },
  { id: 17, name: "Birmingham" },
  { id: 18, name: "Boston" },
  { id: 19, name: "Brasília" },
  { id: 20, name: "Brisbane" },
  { id: 21, name: "Brussels" },
  { id: 22, name: "Budapest" },
  { id: 23, name: "Buenos Aires" },
  { id: 24, name: "Cairo" },
  { id: 25, name: "Calgary" },
  { id: 26, name: "Cape Town" },
  { id: 27, name: "Caracas" },
  { id: 28, name: "Casablanca" },
  { id: 29, name: "Charlotte" },
  { id: 30, name: "Chennai" },
  { id: 31, name: "Chicago" },
  { id: 32, name: "Chongqing" },
  { id: 33, name: "Copenhagen" },
  { id: 34, name: "Curitiba" },
  { id: 35, name: "Dallas" },
  { id: 36, name: "Darwin" },
  { id: 37, name: "Delhi" },
  { id: 38, name: "Denver" },
  { id: 39, name: "Detroit" },
  { id: 40, name: "Dhaka" },
  { id: 41, name: "Dubai" },
  { id: 42, name: "Dublin" },
  { id: 43, name: "Durban" },
  { id: 44, name: "Frankfurt" },
  { id: 45, name: "Fukuoka" },
  { id: 46, name: "Gold Coast" },
  { id: 47, name: "Guangzhou" },
  { id: 48, name: "Hamburg" },
  { id: 49, name: "Hangzhou" },
  { id: 50, name: "Helsinki" },
  { id: 51, name: "Ho Chi Minh City" },
  { id: 52, name: "Hong Kong" },
  { id: 53, name: "Houston" },
  { id: 54, name: "Hyderabad" },
  { id: 55, name: "Istanbul" },
  { id: 56, name: "Jakarta" },
  { id: 57, name: "Jeddah" },
  { id: 58, name: "Johannesburg" },
  { id: 59, name: "Karachi" },
  { id: 60, name: "Kathmandu" },
  { id: 61, name: "Kolkata" },
  { id: 62, name: "Lagos" },
  { id: 63, name: "Lahore" },
  { id: 64, name: "Lucknow" },
  { id: 65, name: "Lima" },
  { id: 66, name: "London" },
  { id: 67, name: "Los Angeles" },
  { id: 68, name: "Madrid" },
  { id: 69, name: "Manila" },
  { id: 70, name: "Melbourne" },
  { id: 71, name: "Mexico City" },
  { id: 72, name: "Miami" },
  { id: 73, name: "Milan" },
  { id: 74, name: "Minneapolis" },
  { id: 75, name: "Montreal" },
  { id: 76, name: "Moscow" },
  { id: 77, name: "Mumbai" },
  { id: 78, name: "Munich" },
  { id: 79, name: "Nairobi" },
  { id: 80, name: "Nanjing" },
  { id: 81, name: "New Delhi" },
  { id: 82, name: "New York" },
  { id: 83, name: "Ningbo" },
  { id: 84, name: "Osaka" },
  { id: 85, name: "Paris" },
  { id: 86, name: "Perth" },
  { id: 87, name: "Philadelphia" },
  { id: 88, name: "Phoenix" },
  { id: 89, name: "Porto Alegre" },
  { id: 90, name: "Prague" },
  { id: 91, name: "Pune" },
  { id: 92, name: "Quebec City" },
  { id: 93, name: "Quito" },
  { id: 94, name: "Recife" },
  { id: 95, name: "Rio de Janeiro" },
  { id: 96, name: "Riyadh" },
  { id: 97, name: "Rome" },
  { id: 98, name: "Rotterdam" },
  { id: 99, name: "Salvador" },
  { id: 100, name: "San Antonio" },
  { id: 101, name: "San Diego" },
  { id: 102, name: "San Francisco" },
  { id: 103, name: "Santiago" },
  { id: 104, name: "São Paulo" },
  { id: 105, name: "Seattle" },
  { id: 106, name: "Seoul" },
  { id: 107, name: "Shanghai" },
  { id: 108, name: "Shenzhen" },
  { id: 109, name: "Singapore" },
  { id: 110, name: "Stockholm" },
  { id: 111, name: "Sydney" },
  { id: 112, name: "Taipei" },
  { id: 113, name: "Tehran" },
  { id: 114, name: "Tel Aviv" },
  { id: 115, name: "Tokyo" },
  { id: 116, name: "Toronto" },
  { id: 117, name: "Vancouver" },
  { id: 118, name: "Vienna" },
  { id: 119, name: "Warsaw" },
  { id: 120, name: "Washington" },
  { id: 121, name: "Wuhan" },
  { id: 122, name: "Xi'an" },
  { id: 123, name: "Zürich" },
  { id: 124, name: "Bhaktapur" },
];
